### ISSUE TITLE
Smart ESC does not recognise a signal

### ISSUE THREAD

**Issue by ParkerEde** [dgatf/msrc#174]
I have tried to use a Smart ESC via a Frsky as well as via Jeti. After switching on, the ESC beeps cyclically and signals that it is not receiving a signal. I used the firmware 1.4.4 and the corresponding configuration tool. Enclosed are the logs.

[Frsky-S.Port-SmartESC.log](https://github.com/user-attachments/files/21302456/Frsky-S.Port-SmartESC.log)

[Jeti-SmartESC.log](https://github.com/user-attachments/files/21302458/Jeti-SmartESC.log)

I followed the wiring exactly.
There's just one thing I'm not quite sure about. Do PIN 12 and PIN13 have to be bridged to the signal connection of the throttle channel of the receiver? Or is it sufficient to use only PIN12, as I don't use thrust reverser?

**Comment by dgatf** [comment]
I'll check it. No, you don't need to connect anything to gpio 13 if reverse is not used.

**Comment by ParkerEde** [comment]
When I recorded the LOG, I also moved the throttle stick. Thr is always set to 0, so that should be the error.
I have also connected the Smart ESC directly to the receiver throttle channel for testing, then the controller switches freely. So that can't be the problem. I then connected the GAS SignalPIN from the RX to GPIO12 and GPIO 4&5 to the signal line to the SmartESC.

**Comment by dgatf** [comment]
Yes, I can reproduce. I'll let you know when fixed.

Have you tried  version 1.3 and higher?

**Comment by ParkerEde** [comment]
I've tried only1.4.4

**Comment by dgatf** [comment]
There was some issues with the new capture edge library. Fixed with commit e91f244.

Please try latest [binaries](https://github.com/dgatf/msrc/wiki/01.-Binaries) (firmware & MSRC Link)

**Comment by ParkerEde** [comment]
Thank you very much. I will check this as soon as possible and report back.

**Comment by dgatf** [comment]
I assume the issue is solved. Otherwise reopen this issue and provide feedback.

**Comment by ParkerEde** [comment]
Yes, now it works.
However, I still have problems with the display of the current, when 1A is measured, 2.82A is displayed in the radio and also in the LOG. Can the value still be calibrated?

**Comment by dgatf** [comment]
That's an issue of the SmartESC current sensor. The current is delivered with 2 decimals precision. MSRC  can't adjust that mismatch. However that's a low current value and current sensors are less accurate at low current levels. Measure the current over 10A and check the mismatch at that level. I expect the mismatch be much lower in percent at higher current levels.

With opentx/edgetx you can set an offset and a ratio on the telemetry sensors.
